import { ConfiguracionVisual } from '../../domain/entities/ConfiguracionVisual';
import { ConfiguracionVisualResponseDTO } from '../dto/configuracion/ConfiguracionVisualDTOs';

export class ConfiguracionVisualMapper {
  public static toDomain(raw: any): ConfiguracionVisual {
    return new ConfiguracionVisual({
      id: raw.id,
      nombreMunicipio: raw.nombreMunicipio,
      nombreSecretaria: raw.nombreSecretaria,
      lema: raw.lema,
      nitAlcaldia: raw.nitAlcaldia,
      logoUrl: raw.logoUrl,
      logoSecundarioUrl: raw.logoSecundarioUrl,
      escudoUrl: raw.escudoUrl,
      faviconUrl: raw.faviconUrl,
      bannerLoginUrl: raw.bannerLoginUrl,
      colorPrimario: raw.colorPrimario,
      colorSecundario: raw.colorSecundario,
      colorAcento: raw.colorAcento,
      colorFondo: raw.colorFondo,
      colorSidebar: raw.colorSidebar,
      colorNavbar: raw.colorNavbar,
      colorTexto: raw.colorTexto,
      modoOscuro: raw.modoOscuro,
      estiloBorde: raw.estiloBorde,
      fuentePrincipal: raw.fuentePrincipal,
      presetTema: raw.presetTema,
      telefonoContacto: raw.telefonoContacto,
      correoContacto: raw.correoContacto,
      direccionSede: raw.direccionSede,
      textoPiePagina: raw.textoPiePagina,
      portalWebUrl: raw.portalWebUrl,
      redesSociales: raw.redesSociales,
      activo: raw.activo,
      createdAt: raw.createdAt,
      updatedAt: raw.updatedAt,
    });
  }

  public static toDTO(entity: ConfiguracionVisual): ConfiguracionVisualResponseDTO {
    return {
      id: entity.id,
      nombreMunicipio: entity.nombreMunicipio,
      nombreSecretaria: entity.nombreSecretaria,
      lema: entity.lema,
      nitAlcaldia: entity.nitAlcaldia,
      logoUrl: entity.logoUrl,
      logoSecundarioUrl: entity.logoSecundarioUrl,
      escudoUrl: entity.escudoUrl,
      faviconUrl: entity.faviconUrl,
      bannerLoginUrl: entity.bannerLoginUrl,
      colorPrimario: entity.colorPrimario,
      colorSecundario: entity.colorSecundario,
      colorAcento: entity.colorAcento,
      colorFondo: entity.colorFondo,
      colorSidebar: entity.colorSidebar,
      colorNavbar: entity.colorNavbar,
      colorTexto: entity.colorTexto,
      modoOscuro: entity.modoOscuro,
      estiloBorde: entity.estiloBorde,
      fuentePrincipal: entity.fuentePrincipal,
      presetTema: entity.presetTema,
      telefonoContacto: entity.telefonoContacto,
      correoContacto: entity.correoContacto,
      direccionSede: entity.direccionSede,
      textoPiePagina: entity.textoPiePagina,
      portalWebUrl: entity.portalWebUrl,
      redesSociales: entity.redesSociales,
      activo: entity.activo,
      updatedAt: entity.updatedAt ? entity.updatedAt.toISOString() : undefined,
    };
  }

  public static toPersistence(entity: ConfiguracionVisual): any {
    return {
      nombreMunicipio: entity.nombreMunicipio,
      nombreSecretaria: entity.nombreSecretaria,
      lema: entity.lema,
      nitAlcaldia: entity.nitAlcaldia,
      logoUrl: entity.logoUrl,
      logoSecundarioUrl: entity.logoSecundarioUrl,
      escudoUrl: entity.escudoUrl,
      faviconUrl: entity.faviconUrl,
      bannerLoginUrl: entity.bannerLoginUrl,
      colorPrimario: entity.colorPrimario,
      colorSecundario: entity.colorSecundario,
      colorAcento: entity.colorAcento,
      colorFondo: entity.colorFondo,
      colorSidebar: entity.colorSidebar,
      colorNavbar: entity.colorNavbar,
      colorTexto: entity.colorTexto,
      modoOscuro: entity.modoOscuro,
      estiloBorde: entity.estiloBorde,
      fuentePrincipal: entity.fuentePrincipal,
      presetTema: entity.presetTema,
      telefonoContacto: entity.telefonoContacto,
      correoContacto: entity.correoContacto,
      direccionSede: entity.direccionSede,
      textoPiePagina: entity.textoPiePagina,
      portalWebUrl: entity.portalWebUrl,
      redesSociales: entity.redesSociales,
      activo: entity.activo,
    };
  }
}
