import { NextResponse } from 'next/server';

const TEMAS_PRESET = [
  {
    id: 'CYAN_MODERN',
    nombre: '⚡ Cyan Cyber Modern (Predeterminado)',
    descripcion: 'Diseño moderno con acentos cyan neón, azul profundo y fondo pizarra.',
    colorPrimario: '#06b6d4',
    colorSecundario: '#2563eb',
    colorAcento: '#4f46e5',
    colorFondo: '#020617',
    colorSidebar: '#0f172a',
    colorNavbar: '#0f172a',
    colorTexto: '#f8fafc',
    modoOscuro: true,
    estiloBorde: 'rounded-2xl',
    fuentePrincipal: 'Outfit',
  },
  {
    id: 'GOV_COLOMBIA',
    nombre: '🇨🇴 Institucional Gobierno Colombia',
    descripcion: 'Paleta solemne de la rama ejecutiva con Azul Institucional (#003366), Oro (#D4AF37) y toques patrios.',
    colorPrimario: '#003366',
    colorSecundario: '#D4AF37',
    colorAcento: '#b45309',
    colorFondo: '#0a1128',
    colorSidebar: '#001f3f',
    colorNavbar: '#002855',
    colorTexto: '#f8fafc',
    modoOscuro: true,
    estiloBorde: 'rounded-xl',
    fuentePrincipal: 'Inter',
  },
  {
    id: 'EMERALD_ECO',
    nombre: '🌿 Valle Verde & Movilidad Sostenible',
    descripcion: 'Inspirado en municipios verdes, eco-movilidad y transporte limpio.',
    colorPrimario: '#10b981',
    colorSecundario: '#059669',
    colorAcento: '#047857',
    colorFondo: '#022c22',
    colorSidebar: '#064e3b',
    colorNavbar: '#064e3b',
    colorTexto: '#f0fdf4',
    modoOscuro: true,
    estiloBorde: 'rounded-2xl',
    fuentePrincipal: 'Outfit',
  },
  {
    id: 'ROYAL_NAVY',
    nombre: '🏛️ Distrito Capital / Royal Navy',
    descripcion: 'Estilo corporativo sobrio con azul zafiro, azul marino y acentos celestes.',
    colorPrimario: '#3b82f6',
    colorSecundario: '#1d4ed8',
    colorAcento: '#60a5fa',
    colorFondo: '#090d16',
    colorSidebar: '#111827',
    colorNavbar: '#111827',
    colorTexto: '#f9fafb',
    modoOscuro: true,
    estiloBorde: 'rounded-2xl',
    fuentePrincipal: 'Inter',
  },
  {
    id: 'AMBER_WARM',
    nombre: '☀️ Sol & Tierra / Valle Dorado',
    descripcion: 'Tonalidades cálidas de sol, ámbar dorado, madera y calidez ciudadana.',
    colorPrimario: '#f59e0b',
    colorSecundario: '#d97706',
    colorAcento: '#b45309',
    colorFondo: '#18120c',
    colorSidebar: '#271b11',
    colorNavbar: '#271b11',
    colorTexto: '#fffbeb',
    modoOscuro: true,
    estiloBorde: 'rounded-2xl',
    fuentePrincipal: 'Montserrat',
  },
  {
    id: 'CRIMSON_METRO',
    nombre: '🌆 Metropolitano Crimson & Seguridad Vial',
    descripcion: 'Enfoque de alto contraste en prevención vial con rojo carmesí, rubí y antracita.',
    colorPrimario: '#e11d48',
    colorSecundario: '#be123c',
    colorAcento: '#9f1239',
    colorFondo: '#0f0b0d',
    colorSidebar: '#1c1317',
    colorNavbar: '#1c1317',
    colorTexto: '#fff1f2',
    modoOscuro: true,
    estiloBorde: 'rounded-xl',
    fuentePrincipal: 'Outfit',
  },
  {
    id: 'PURPLE_TECH',
    nombre: '🟣 Smart City & Tránsito Digital',
    descripcion: 'Paleta vanguardista basada en Smart Cities con violeta, índigo y fucsia tecnológico.',
    colorPrimario: '#8b5cf6',
    colorSecundario: '#7c3aed',
    colorAcento: '#a855f7',
    colorFondo: '#0f0a1c',
    colorSidebar: '#170f2b',
    colorNavbar: '#170f2b',
    colorTexto: '#faf5ff',
    modoOscuro: true,
    estiloBorde: 'rounded-3xl',
    fuentePrincipal: 'Outfit',
  },
  {
    id: 'LIGHT_INSTITUTIONAL',
    nombre: '🏛️ Modo Claro Ejecutivo & Transparente',
    descripcion: 'Diseño claro de alta legibilidad para ventanillas de atención e impresión.',
    colorPrimario: '#0284c7',
    colorSecundario: '#0369a1',
    colorAcento: '#0f172a',
    colorFondo: '#f8fafc',
    colorSidebar: '#ffffff',
    colorNavbar: '#ffffff',
    colorTexto: '#0f172a',
    modoOscuro: false,
    estiloBorde: 'rounded-xl',
    fuentePrincipal: 'Inter',
  },
];

export async function GET() {
  return NextResponse.json(TEMAS_PRESET);
}
